#
# Config for dsTitle plugin
# For the different text colors and styles, go to
# http://www.minecraftwiki.net/wiki/Formatting_codes
# (but replace the '§' with a '&')
# Be aware to use spaces, not tabs.
#
general:
  # Should the plugin set the chatformat to the one specified in this config?
  overwrite_format: false
  # The charformat used when overwrite_format is true
  # %1$s will be replaced with the playername, %2$s with the message and
  # {title} with the title
  chat_format: '<{titleprefix}%1$s{titlesuffix}> %2$s'
  # Should the plugin show all unavailable titles when a player does /title list ?
  show_unavailable_titles: true
messages:
  # I think this doesn't need explanation
  error_no_player: '&8[&eTitles&8] &cOnly players can use this command'
  error_no_permission: '&8[&eTitles&8] &cYou don`t have enough permissions for this command'
  error_no_vault: '&8[&eTitles&8] &cVault needs to be installed/enabled to use this command'
  error_title_not_found: '&8[&eTitles&8] &cThat title is not found!'
  title_set: '&8[&eTitles&8] &eTitle set!'
  title_cleared: '&8[&eTitles&8] &eTitle cleared!'
  title_granted: '&8[&eTitles&8] &eTitle &f{title} &egranted to &f{name}&e.'
  title_ungranted: '&8[&eTitles&8] &eTitle &f{title} &eungranted from &f{name}&e.'
  reloaded: '&8[&eTitles&8] &eConfig reloaded'
  # Header showed above unavailable titles, when a player does /title list
  unavailable_header: '&8~~=={  &cUnavailable &etitles &8}==~~'
  # Header showed above available titles, when a player does /title list
  available_header: '&8~~=={  &aAvailable &etitles &8}==~~'
  # Make up of one title in the list showed when a player does /title list
  title_listitem: '{name} ({preview}) {description}'
  # The help menu (if you just use /title)
  menu_header: '&8~~=={ &e&ldsTitles help &r&8}==~~'
  menu_list: ' &e/title list &fList available titles'
  menu_set: ' &e/title set <title> &fSet your title'
  menu_clear: ' &e/title clear &fClear your title'
  menu_grant: ' &e/title grant <player> <title> &fGrant a title to a player'
  menu_ungrant: ' &e/title ungrant <player> <title> &fUngrant a title from a player'
  menu_reload: ' &e/title reload &fReload the config'