name: dsTitle
main: denniss17.dsTitle.DS_Title
version: 1.2.1
author: Denniss17
website: 'http://dev.bukkit.org/server-mods/dstitle/'
description: With this plugin you can create and set titles.
softdepend: [Vault]
commands:
   title:
      description: Manage your title
      usage: /<command>
      permission: ds_title.title
permissions:
   ds_title.admin:
      description: Permission for all commands.
      default: op
      children:
         ds_title.player: true
   ds_title.player:
      description: Gives access to all the player commands
      default: true
      children:
        ds_title.title: true