#
# This is the config file where you put the title
# These have to be in the following format:
# titles:
#   <name>:
#     prefix: <prefix>
#     suffix: <suffix>
#     headprefix: <prefix>
#     headsuffix: <suffix>
#     permission: <permission needed>
#     description: <description>
#
# Permission and description are optional.
#
titles: 